Update animal.py
skeith/MayuYukirin pull request #13
Opened 2021-04-29 13:46 UTC by dupontjean

added big cats

2021-05-25 17:24 UTC, HTML-CODDER reviewed
Update animal.py #13

2021-05-26 01:12 UTC, skeith requested changes
Change the variable name for consistency

2021-05-26 01:12 UTC, skeith commented on animal/animal.py
> +bigcat = "http://randombig.cat/roar.json"
change this to `roarapi` for consistency

2021-05-26 01:12 UTC, skeith commented on animal/animal.py
> +        self.bigcat = bigcat
which means, this and subsequent occurrence should be changed to `self.roarapi`

2021-06-05 09:34 UTC, closed without merging